#!/usr/bin/env python3
"""
Renders a scalable font into the bitmap the terminal draws with.

The loader cannot rasterise anything at runtime, so the font it uses has to be
a table of bits somebody produced beforehand. This produces it, and is checked
in beside what it produced so the table can be regenerated rather than edited
by hand — editing bitmaps by hand is how a font ends up with one glyph that is
subtly wrong and nobody notices for a year.

    tools/make-font.py JetBrainsMono-Regular.ttf src/terminal/font8x16.c

Every glyph must fall inside its cell. Anything that would be clipped is an
error rather than a warning: a font that loses the tail of a 'g' is not one to
put on a screen somebody is reading a failure from.

Needs Pillow, and only when the font is regenerated.
"""

import sys

from PIL import Image, ImageDraw, ImageFont

CELL_WIDTH = 8
CELL_HEIGHT = 16
FIRST = 0x20
LAST = 0x7E

# The size and the corner the glyph is drawn from, chosen so that the capitals
# and the descenders both fit the cell with a row to spare at each end.
POINT_SIZE = 13
ORIGIN_X = 0
ORIGIN_Y = -1

# Room around the cell, so a glyph that does not fit is measured rather than
# quietly cut off at the edge of the image.
MARGIN = 8


def draw(font, character, width, height, x, y):
    """One character as a list of rows of bits, most significant bit leftmost."""
    image = Image.new("1", (width, height), 0)
    canvas = ImageDraw.Draw(image)
    canvas.fontmode = "1"  # No antialiasing: a pixel is on or it is not.
    canvas.text((x, y), character, font=font, fill=1)

    pixels = image.load()
    rows = []
    for row in range(height):
        bits = 0
        for column in range(width):
            if pixels[column, row]:
                bits |= 0x80 >> column if column < 8 else 0
        rows.append((bits, [pixels[c, row] for c in range(width)]))
    return rows


def clipped(font, character):
    """The pixels that would fall outside the cell, if any."""
    outside = 0
    rows = draw(font, character, CELL_WIDTH + 2 * MARGIN, CELL_HEIGHT + 2 * MARGIN,
                ORIGIN_X + MARGIN, ORIGIN_Y + MARGIN)
    for row, (_, columns) in enumerate(rows):
        for column, lit in enumerate(columns):
            if not lit:
                continue
            if not (MARGIN <= column < MARGIN + CELL_WIDTH):
                outside += 1
            elif not (MARGIN <= row < MARGIN + CELL_HEIGHT):
                outside += 1
    return outside


def glyphs(path):
    font = ImageFont.truetype(path, POINT_SIZE)
    table = {}
    for code in range(FIRST, LAST + 1):
        character = chr(code)
        lost = clipped(font, character)
        if lost:
            raise SystemExit(
                f"{character!r} loses {lost} pixels to the edge of its cell")
        rows = draw(font, character, CELL_WIDTH, CELL_HEIGHT, ORIGIN_X, ORIGIN_Y)
        table[character] = [bits for bits, _ in rows]
    return table


def preview(table, text):
    lines = ["" for _ in range(CELL_HEIGHT)]
    for character in text:
        rows = table.get(character, [0] * CELL_HEIGHT)
        for row in range(CELL_HEIGHT):
            lines[row] += "".join(
                "#" if rows[row] & (0x80 >> column) else "."
                for column in range(CELL_WIDTH))
    return "\n".join(lines)


HEADER = """#include "terminal/font8x16.h"

/*
 * Eight by sixteen, one byte per row, most significant bit leftmost.
 *
 * Generated by tools/make-font.py from JetBrains Mono, which is the font the
 * system this loads uses everywhere else, so the machine reads the same from
 * the first line it prints to the last. Do not edit: regenerate.
 *
 * JetBrains Mono is under the SIL Open Font License 1.1.
 *
 * Covers the printable range and no more. A loader prints paths, numbers and
 * short sentences; anything outside this the terminal draws as a filled block,
 * which is visible, and being visible is the whole point.
 */
static const uint8_t glyphs[FONT8X16_COUNT * FONT8X16_HEIGHT] = {
"""

FOOTER = """};

static const struct terminal_font font = {
    .glyphs = glyphs,
    .width = FONT8X16_WIDTH,
    .height = FONT8X16_HEIGHT,
    .first = FONT8X16_FIRST,
    .count = FONT8X16_COUNT,
};

const struct terminal_font *font8x16(void) {
    return &font;
}
"""


def emit(table):
    out = [HEADER]
    for code in range(FIRST, LAST + 1):
        character = chr(code)
        rows = table[character]
        name = character if character != " " else "space"
        for half in (0, 8):
            out.append("    " + " ".join(f"0x{bits:02X}," for bits in rows[half:half + 8]))
            out.append(f" /* {name} */\n" if half else "\n")
    out.append(FOOTER)
    return "".join(out)


def main():
    if len(sys.argv) not in (2, 3):
        raise SystemExit(f"usage: {sys.argv[0]} FONT.ttf [OUTPUT.c]")

    table = glyphs(sys.argv[1])
    if len(sys.argv) == 2:
        print(preview(table, "[INFO] loading /boot/tunix"))
        print(preview(table, "Wgjqy 0123 {|} @#$%"))
        return

    with open(sys.argv[2], "w", newline="\n") as output:
        output.write(emit(table))


if __name__ == "__main__":
    main()
